package router

import (
	"fanapi/internal/handler"
	"fanapi/internal/middleware"

	"github.com/gin-gonic/gin"
)

func registerAdminRoutes(authed *gin.RouterGroup, deps Dependencies) {
	admin := authed.Group("/admin")
	admin.Use(middleware.Admin())
	{
		admin.POST("/channels", handler.CreateChannel)
		admin.GET("/channels", handler.ListChannels)
		admin.PUT("/channels/:id", handler.UpdateChannel)
		admin.PATCH("/channels/:id/active", handler.PatchChannelActive)
		admin.POST("/channels/:id/refresh-runtime", handler.RefreshChannelRuntime)
		admin.DELETE("/channels/:id", handler.DeleteChannel)

		admin.GET("/key-pools", handler.ListKeyPools)
		admin.POST("/key-pools", handler.CreateKeyPool)
		admin.DELETE("/key-pools/:id", handler.DeleteKeyPool)
		admin.PATCH("/key-pools/:id/toggle", handler.ToggleKeyPool)
		admin.PATCH("/key-pools/:id/vendor-toggle", handler.ToggleVendorSubmittable)
		admin.GET("/key-pools/:id/keys", handler.ListPoolKeys)
		admin.POST("/key-pools/:id/keys", handler.AddPoolKey)
		admin.POST("/key-pools/:id/keys/import", handler.ImportPoolKeys)
		admin.GET("/key-pools/:id/channels", handler.GetKeyPoolChannels)
		admin.DELETE("/pool-keys/:id", handler.RemovePoolKey)
		admin.PATCH("/pool-keys/:id", handler.UpdatePoolKey)
		admin.PATCH("/pool-keys/:id/vendor", handler.AdminSetPoolKeyVendor)

		admin.GET("/users", handler.ListUsers)
		admin.POST("/users", handler.CreateUser)
		admin.POST("/users/batch", handler.BatchUpdateUsers)
		admin.DELETE("/users/:id", handler.DeleteUser)
		admin.POST("/users/:id/recharge", handler.Recharge)
		admin.POST("/users/:id/model-credits", handler.GrantModelCredit)
		admin.GET("/users/:id/model-credits", handler.AdminListModelCredits)
		admin.POST("/users/:id/refresh-vip", handler.RefreshUserVIPGroup)
		admin.PUT("/users/:id/vip-group", handler.SetUserVIPGroup)
		admin.PUT("/users/:id/password", handler.ResetUserPassword)
		admin.PUT("/users/:id/group", handler.SetUserGroup)
		admin.PUT("/users/:id/role", handler.SetUserRole)
		admin.PUT("/users/:id/rebate-ratio", handler.SetUserRebateRatio)
		admin.PATCH("/users/:id/freeze", handler.FreezeUser)

		admin.GET("/transactions", handler.ListAllTransactions)
		admin.GET("/vip-groups", handler.ListVIPGroups)
		admin.POST("/vip-groups", handler.CreateVIPGroup)
		admin.POST("/vip-groups/refresh-users", handler.RefreshAllUserVIPGroups)
		admin.PUT("/vip-groups/:id", handler.UpdateVIPGroup)
		admin.DELETE("/vip-groups/:id", handler.DeleteVIPGroup)
		admin.GET("/tasks", handler.ListTasks)
		admin.GET("/tasks/:id", handler.GetAdminTask)
		admin.GET("/cleanup/preview", handler.AdminPreviewCleanup)
		admin.POST("/cleanup/run", handler.AdminRunCleanup)
		admin.GET("/stats", handler.GetAdminStats)
		admin.GET("/stats/trend", handler.GetAdminStatsTrend)
		admin.GET("/stats/top", handler.GetAdminStatsTop)

		admin.POST("/cards/generate", handler.GenerateCards)
		admin.GET("/cards", handler.ListCards)
		admin.DELETE("/cards/:id", handler.DeleteCard)
		admin.GET("/llm-logs", handler.AdminListLLMLogs)
		admin.GET("/llm-logs/:id", handler.AdminGetLLMLog)
		admin.GET("/settings", handler.GetSettings)
		admin.PUT("/settings", handler.UpdateSettings)
		admin.POST("/verify-password", handler.AdminVerifyPassword)
		admin.GET("/me", handler.GetAdminMe)

		admin.GET("/vendors", handler.AdminListVendors)
		admin.PATCH("/vendors/:id", handler.AdminUpdateVendor)
		admin.GET("/resellers", handler.AdminListResellers)
		admin.POST("/resellers", handler.AdminCreateReseller)
		admin.PATCH("/resellers/:id", handler.AdminUpdateReseller)
		admin.GET("/reseller-sites", handler.AdminListResellerSites)
		admin.GET("/reseller-site-build-jobs", handler.AdminListResellerSiteBuildJobs)
		admin.POST("/reseller-site-build-jobs/:id/retry", handler.AdminRetryResellerBuildJob)

		admin.GET("/withdrawals", handler.AdminListWithdrawals)
		admin.GET("/withdrawals/pending-count", handler.AdminPendingWithdrawCount)
		admin.POST("/withdrawals/:id/approve", handler.AdminApproveWithdrawal)
		admin.POST("/withdrawals/:id/reject", handler.AdminRejectWithdrawal)
		admin.POST("/withdrawals/:id/cs-approve", handler.AdminCsApproveWithdrawal)
		admin.POST("/withdrawals/:id/proof", handler.AdminUploadWithdrawalProof)

		admin.POST("/channels/batch", handler.BatchUpdateChannels)
		admin.GET("/channels/:id/health", handler.GetChannelHealth)
		admin.GET("/channels/:id/logs", handler.ListChannelLogs)
		admin.GET("/channels/:id/upstream-cost", handler.PreviewChannelUpstreamCost)
		admin.POST("/channels/:id/sync-upstream-cost", handler.SyncChannelUpstreamCost)

		admin.GET("/users/:id/referrals", handler.GetUserReferrals)
		admin.GET("/users/:id/portrait", handler.GetUserPortrait)
		admin.GET("/users/:id/operation-log", handler.GetUserOperationLog)
		admin.POST("/users/:id/risk-labels", handler.AddRiskLabel)
		admin.DELETE("/risk-labels/:id", handler.DeleteRiskLabel)
		admin.GET("/api-keys", handler.AdminListAPIKeys)
		admin.PATCH("/api-keys/:id/revoke", handler.RevokeAPIKey)

		admin.GET("/transactions/aggregate", handler.GetTransactionAggregate)
		admin.POST("/transactions/adjust", handler.AdjustTransaction)
		admin.POST("/transactions/sync-user-balance", handler.SyncUserBalanceFromRedis)

		admin.GET("/cards/batches", handler.ListCardBatches)
		admin.POST("/cards/:id/void", handler.VoidCard)
		admin.POST("/cards/batches/:batch_id/void", handler.VoidCardBatch)

		admin.GET("/audit", handler.ListAuditLogs)
		admin.GET("/notifications", handler.ListNotifications)
		admin.POST("/notifications", handler.CreateNotification)
		admin.POST("/notifications/:id/send", handler.SendNotification)
		admin.DELETE("/notifications/:id", handler.DeleteNotification)

		admin.GET("/alerts", handler.ListAlerts)
		admin.PATCH("/alerts/:id/ack", handler.AckAlert)
		admin.PATCH("/alerts/:id/resolve", handler.ResolveAlert)

		admin.GET("/exports", handler.ListExportTasks)
		admin.POST("/exports", handler.CreateExportTask)

		admin.GET("/upstream-platforms", handler.ListUpstreamPlatforms)
		admin.POST("/upstream-platforms", handler.CreateUpstreamPlatform)
		admin.PUT("/upstream-platforms/:id", handler.UpdateUpstreamPlatform)
		admin.DELETE("/upstream-platforms/:id", handler.DeleteUpstreamPlatform)
		admin.GET("/upstream-platforms/:id/models", handler.GetUpstreamModels)
		admin.GET("/upstream-platforms/:id/channel-bindings/preview", handler.PreviewUpstreamPlatformChannelBindings)
		admin.POST("/upstream-platforms/:id/bind-channels", handler.BindUpstreamPlatformChannels)
		admin.POST("/upstream-platforms/:id/sync-balance", handler.SyncUpstreamPlatformBalance)
		admin.POST("/upstream-platforms/:id/sync-channels", handler.SyncUpstreamPlatformChannels)
		admin.POST("/upstream-platforms/:id/api-keys", handler.CreateUpstreamAPIKey)
		admin.POST("/channels/batch-from-upstream", handler.BatchCreateChannelsFromUpstream)

		admin.GET("/roles", handler.ListRoles)
		admin.POST("/roles", handler.CreateRole)
		admin.PUT("/roles/:id", handler.UpdateRole)
		admin.DELETE("/roles/:id", handler.DeleteRole)
		admin.GET("/admins", handler.ListAdminUsers)
		admin.PUT("/admins/:id/roles", handler.SetAdminRoles)

		admin.GET("/coupons", handler.ListCoupons)
		admin.POST("/coupons", handler.CreateCoupon)
		admin.DELETE("/coupons/:id", handler.VoidCoupon)
		admin.GET("/coupons/:id/uses", handler.ListCouponUses)
		admin.GET("/payments", handler.AdminListPaymentOrders)
		admin.GET("/settings/logs", handler.ListSettingLogs)
	}
}
